# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
common: &common

development:
  <<: *common
  payjp_public_key: 'pk_test_91c45c7a7d3956833bb3b43c'
  payjp_private_key: 'sk_test_339e75404e6c16765168b649'
  payjp_webhook_token: 'whook_510298e04ffa8653af85e0b28d'

test:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  payjp_public_key: 'pk_live_dad1abc323f39804dfc051df'
  payjp_private_key: 'sk_live_67fcf1dfddff742faa0a05a73109ae14ccccbbdf7c0f76e023bc8995'
  payjp_webhook_token: 'whook_510298e04ffa8653af85e0b28d'

